default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  username: bombinsky
  password:

development:
  <<: *default
  database: service-a_development

test:
  <<: *default
  database: service-a_test

production:
  <<: *default
  database: service-a_production
